<?php
/*
 * Implements hook_form_BASE_FORM_ID_alter()
 */
function carenet_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
    //drupal_add_js(array('carenet_profile' => array('key' => 'value')), 'setting');
    drupal_add_js(drupal_get_path('module', 'carenet_profile') . '/js/carenet_profile.js');
    dpm($form);
    dpm($form_state);
    $form['actions']['submit']['#value'] = 'Save Draft';
    $destination = 'users';
    $form['actions']['cancel'] = array(
        '#type' => 'button',
        '#value' => t('Cancel'),
        '#weight' => 20,
        '#submit' => array('carenet_profile_form_cancel'),
    );
    $form['actions']['preview'] = array(
        '#type' => 'submit',
        '#value' => t('Sign'),
        '#weight' => 10,
        '#submit' => array('carenet_profile_form_sign'),
    );
    $form['some_text']['#markup'] = 'I, as the designated Office Administrator, certify that the information provided above is true and correct as of the date on this application';
    $form['some_text']['#weight'] = 100;
}
/**
 * cancel_button callback.
 */
function carenet_profile_form_cancel($form, &$form_state) {
    dpm('carenet_profile_form_cancel');
    $url = 'users';
    drupal_goto($url);
}
/**
 * cancel_button callback.
 */
function carenet_profile_form_sign($form, &$form_state) {
    dpm('carenet_profile_form_sign');
}