<?php
/*
 * Implements hook_form_BASE_FORM_ID_alter()
 */
function carenet_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
    dpm($form);
    dpm($form_state);
    $form['actions']['submit']['#value'] = 'Save Draft';
    $form['some_text']['#markup'] = 'I, as the designated Office Administrator, certify that the information provided above is true and correct as of the date on this application';
    $form['some_text']['#weight'] = 100;
}