<?php
/**
 * @file
 * Drupal needs this blank file.
 */


/**
 * Implements hook_menu()
 */
function carenet_user_menu() {
  $items['admin/carenet-manage'] = array(
    'title' => 'Manage content',
    'description' => 'Carenet manage content',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('access carenet-manage page'),
  );
  return $items;
}

/*
 * Implements hook_permission
 */

function carenet_user_permission() {
  return array(
    'access carenet-manage page' => array(
      'title' => t('Access carenet manage page'),
      'description' => t('Access carenet manage page'),
    ),
  );
}