<?php
/**
 * @file
 * Drupal needs this blank file.
 */


/**
 * Implements hook_menu()
 */
function carenet_user_menu() {
  $items['admin/carenet-manage'] = array(
    'title' => 'Manage content',
    'description' => 'Carenet manage content',
    'weight' => -10,
    'page callback' => 'carenet_manage_page',
    'access arguments' => array('access carenet-manage page'),
    'file' => 'carenet_user.pages.inc',
  );
  $items['admin/carenet-manage/content'] = array(
    'title' => 'Manage content',
    'description' => 'Carenet manage content',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
}

/*
 * Implements hook_permission
 */

function carenet_user_permission() {
  return array(
    'access carenet-manage page' => array(
      'title' => t('Access carenet manage page'),
      'description' => t('Access carenet manage page'),
    ),
  );
}