<?php

/**
 * Implements hook_menu()
 */
function carenet_custom_menu() {
  $items['provider-listing'] = array(
    'title' => 'Provider Listing',
    'page callback' => 'carenet_custom_list_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['provider-get-data'] = array(
    'title' => 'Provider Listing',
    'page callback' => 'carenet_custom_get_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/carenet'] = array(
    'title' => 'Carenet',
    'description' => 'Settings for Carenet',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/carenet/provider-active'] = array(
    'title' => 'Provider active',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('carenet_admin_provider_active_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'carenet_custom.admin.inc',
  );
  $items['provider-active/%'] = array(
    'title' => 'Provider active',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('carenet_provider_active_form'),
    'access callback' => TRUE,
    'file' => 'carenet_custom.pages.inc',
  );

  return $items;
}

function carenet_custom_list_data(){
	//drupal_add_js(drupal_get_path('module', 'wb_project').'/js/jquery-1.12.0.min.js', 'file');
	drupal_add_js(drupal_get_path('module', 'carenet_custom').'/js/jquery.dataTables.min.js', 'file');
	drupal_add_js(drupal_get_path('module', 'carenet_custom').'/js/dataTables.select.min.js', 'file');
	drupal_add_js(drupal_get_path('module', 'carenet_custom').'/js/custom.js', 'file');

	drupal_add_css(drupal_get_path('module', 'carenet_custom').'/css/select.dataTables.min.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
	drupal_add_css(drupal_get_path('module', 'carenet_custom').'/css/jquery.dataTables.min.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
	

	$fieldsArr = array('Phone #', 'Provider', 'City', 'County', 'Status', 'View', 'Last Activity');

	$projects_fields = array();

	$output = '<table id="carenet_custom_list_data" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>';
            	foreach ($fieldsArr as $field) {
            		$output .= '<th>'.trim($field).'</th>';
            		$projects_fields[] = array('data' => trim($field));
            	}
        $output .='</tr>
        </thead>
        <tfoot>
            <tr>';
                foreach ($fieldsArr as $field) {
            		$output .= '<th>'.trim($field).'</th>';
            	}
        $output .='</tr>
          </tfoot>
    </table>';
    
  drupal_add_js(array('carenet_custom_list_data_fields' => json_encode($projects_fields)), 'setting');
	return $output;
}

function carenet_custom_get_data(){
	global $base_url;
	$output = '';

	// Add parameter filter
	$parameter = array();
	if(!empty($_POST['search']['value'])){
		$parameter['search_full'] = $_POST['search']['value'];
	}

	if(!empty($_POST['start']) && !empty($_POST['length'])){
		$parameter['page'] = $_POST['start']/$_POST['length'];
	}

	$query = drupal_http_build_query($parameter);

	$url = $base_url.'/provide-listing-data'.$query;

	$data = drupal_json_decode(file_get_contents($url));
	$data_telephone = array();

	foreach ($data['nodes'] as $response_data) {
	  $data_telephone[$response_data['node']['telephone']][] = $response_data['node'];
	}

	$rows = array();
	$i = 1;
	foreach($data_telephone as $key => $phone){
		$provider = array();
		$city = array();
		$county = array();

		foreach($data_telephone[$key] as $item){
			$provider[] = $item['nid'];
			$city[] = $item['city'];
			$county[] = $item['county'];
		}

		$provider = array_unique($provider);
		$city = array_unique($city);
		$county = array_unique($county);

		$rows[] = array('DT_RowId' => $i,
										'Phone #' => $key,
										'Provider' => count($provider),
										'City' => count($city),
										'County' => count($county),
										'Status' => 'New',
										'View' => '<a href="#">View</a>',
										'Last Activity' => '');
		$i++;
	}

	$data_listing['data'] = $rows;
  $data_listing['options'] = '';
  $data_listing['files'] = '';
  $data_listing['recordsTotal'] = $data['pager']['count'];
  $data_listing['recordsFiltered'] = $data['pager']['count'];
  return drupal_json_output($data_listing);
}